### PR TITLE
Hotfix/build

### PR DESCRIPTION
**Pull request by jramapuram**
- add a param for the lib directory
  - fix a bug that will arise when you upgrade to rust 1.3

### CODE REVIEW

**Comment by pavanky** [comment]
Why is it not complaining for the regular integer types?

**Comment by jramapuram** [comment]
Because integers can be upcast. 
Bools are not 0/1 like in cpp.

**Comment by jramapuram** [comment]
Ah no I misunderstood. 
I guess they are allowable to be cast to ints but not floats? Not sure. Will have to dig into rust spec

**Comment by 9prady9** [comment]
Hm, i just checked this and it worked fine in the example.

**Comment by jramapuram** [comment]
Do you have rust 1.3?

**Comment by 9prady9** [comment]
nope, i have 1.1. Are you using nightly ?

**Comment by jramapuram** [comment]
Yes. I'm guessing this will pop up soon in the release builds. This way should be prepped for both cases.

**Pull request merged**
